<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Отчеты о расходовании средств");
?> 				 
<div class="b clear" id="inside">   
  <br />
 На этой странице будут размещены фотоотчеты по доставке помощи детям отказникам, по мере расходования средств. Спасибо Всем кто остался неравнодушным. 
  <p><strong>1) 21.02.07 г</strong> по запросу волонтеров Отказники.Ру были приобретены и доставлены 12 стульчиков для кормления <a class="undefined" title="Детский стульчик" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=4289" target="_blank"><strong>Kolcraft Колкрафт (19542)</strong></a> на сумму <strong>24024 рубля</strong> для нужд детей отказников в больницах Москвы и подмосковья.</p>
 
  <p><strong>2)</strong> <strong>21.06.07 г</strong> в Детский дом № 34 по запросу волонтеров Отказники.Ру, в связи с отключением воды, было приобретено и доставлено<strong> 325 литров</strong> <a class="undefined" title="Детская вода" href="http://www.mladenec-shop.ru/index.php?cat=207013&amp;order=name&amp;all" target="_blank">Детской воды,</a><strong> </strong>на сумму <strong>2853 р.</strong></p>
 
  <p><strong>3) 30.06.07 г</strong> в Детские дома по запросу волонтеров Отказники.Ру было приобретено и доставлено Детское питание (<a class="undefined" title="Детские смеси" href="http://www.mladenec-shop.ru/index.php?cat=207009&amp;order=name&amp;all" target="_blank">детские молочные смеси,</a> <a class="undefined" title="Детские пюре" href="http://www.mladenec-shop.ru/index.php?cat=207011&amp;order=name&amp;all" target="_blank">пюре</a> и <a class="undefined" title="Детские соки" href="http://www.mladenec-shop.ru/index.php?cat=207012&amp;order=name&amp;all" target="_blank">соки</a>) на сумму<strong> 31873 р.</strong><img id="tsb_0.4385464946811871" src="../components/bitrix/menu/images/menu.gif" /></p>
 
  <p><strong>4) 28.06.07 г</strong> были приобретены нашей клиенткой Еленой детские игрушки <a class="undefined" title="Детские игрушки" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=10006" target="_blank">Chicco Чикко игрушка &quot;Телефон Hello Chicco&quot; электронный с 12 мес.</a> и <a class="undefined" title="Детские игрушки" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=4309" target="_blank">Chicco Чикко игрушка &quot;Электронная улитка&quot; с 12 мес.</a> на сумму<strong> 2156 р.</strong> и доставлены службой доставки Младенец.РУ в<strong> </strong>Детскую больницу г. Мытищи <strong>03.07.07 г.</strong></p>
 
  <p><strong>5) 23.08.07 г</strong> в Детский дом по запросу волонтеров Отказники.Ру были приобретены и доставлены <a class="undefined" title="Детские соски" href="http://www.mladenec-shop.ru/index.php?cat=207041&amp;manuf_id=1005&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B172&#37;5D=&amp;filter&#37;5B174&#37;5D=677&amp;filter&#37;5B176&#37;5D=&amp;filter&#37;5B178&#37;5D=&amp;filter&#37;5B180&#37;5D=&amp;filter&#37;5B181&#37;5D=" target="_blank">детские соски для кормления Авент</a> на сумму <strong>9212 рублей.</strong></p>
 
  <p><strong>6) 28.08.07 г</strong> В<strong> </strong>Детский дом по запросу волонтеров Отказники.РУ было приобретено и доставлено <strong>175 литров</strong> <a class="undefined" title="Детская вода" href="http://www.mladenec-shop.ru/index.php?cat=207013&amp;order=name&amp;all" target="_blank">Детской воды</a> на сумму <strong>1536 рублей.</strong></p>
 
  <p><strong>7) 23.11.07 г</strong> В<strong> </strong>Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены Детская косметика (<a class="undefined" title="Детская косметика" href="http://www.mladenec-shop.ru/index.php?cat=207038&amp;manuf_id=1168&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B126&#37;5D=&amp;filter&#37;5B127&#37;5D=" target="_blank">детское мыло,</a> <a class="undefined" title="Детский крем" href="http://www.mladenec-shop.ru/index.php?cat=207049&amp;manuf_id=1175&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B121&#37;5D=&amp;filter&#37;5B122&#37;5D=&amp;filter&#37;5B130&#37;5D=" target="_blank">крем,</a> <a class="undefined" title="Детская присыпка" href="http://www.mladenec-shop.ru/index.php?cat=9350&amp;manuf_id=1167&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B211&#37;5D=&amp;filter&#37;5B212&#37;5D=" target="_blank">присыпка</a>) и Детское питание (<a class="undefined" title="Детские товары" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">детская молочная смесь,</a> <a class="undefined" title="Детские соки" href="http://www.mladenec-shop.ru/index.php?cat=207012&amp;manuf_id=1238&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B57&#37;5D=&amp;filter&#37;5B60&#37;5D=&amp;filter&#37;5B61&#37;5D=&amp;filter&#37;5B62&#37;5D=&amp;filter&#37;5B63&#37;5D=&amp;filter&#37;5B65&#37;5D=&amp;filter&#37;5B68&#37;5D=" target="_blank">соки</a>) на сумму <strong>17128 рублей.</strong></p>
 
  <p><strong>8)</strong> <strong>08.12.07 г</strong> В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детские весы" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=9733" target="_blank">Детские весы Maman</a>, <a title="Детская горка" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=10478" target="_blank">Детские горки &quot;Пеликан&quot;</a> и <a title="Детский стульчик" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=10123" target="_blank">Детские стульчики-трансформеры Литаф 2 в 1</a> на сумму <strong>41106 рублей.</strong></p>
 
  <p><strong>9)</strong> <strong>18.12.07 г</strong> были приобретены нашей клиенткой Оксаной <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">детские подгузники</a> <a title="Детские памперсы" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=9360" target="_blank">(Памперс</a> <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207031" target="_blank">и Либеро) </a>и <a title="Детские салфетки" href="http://www.mladenec-shop.ru/index.php?cat=207036&amp;manuf_id=1051&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B150&#37;5D=&amp;filter&#37;5B151&#37;5D=&amp;filter&#37;5B183&#37;5D=" target="_blank">детские салфетки Хаггис,<strong> </strong></a>на сумму <strong>3072 рубля</strong> для нужд детей отказников в больницах Москвы и подмосковья.</p>
 
  <p><strong>10) 28.12.07 г</strong> по запросу волонтеров Отказники.Ру были приобретены <a title="Детское пюре" href="http://www.mladenec-shop.ru/index.php?cat=207011&amp;manuf_id=&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B42&#37;5D=&amp;filter&#37;5B43&#37;5D=&amp;filter&#37;5B44&#37;5D=&amp;filter&#37;5B45&#37;5D=&amp;filter&#37;5B46&#37;5D=&amp;filter&#37;5B202&#37;5D=&amp;filter&#37;5B287&#37;5D=" target="_blank">Детское пюре</a> (<a title="Детское питание" href="http://www.mladenec-shop.ru/index.php?cat=207011&amp;manuf_id=1145&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B42&#37;5D=&amp;filter&#37;5B43&#37;5D=&amp;filter&#37;5B44&#37;5D=&amp;filter&#37;5B45&#37;5D=&amp;filter&#37;5B46&#37;5D=&amp;filter&#37;5B202&#37;5D=&amp;filter&#37;5B287&#37;5D=" target="_blank">Бабушкино лукошко</a> и <a title="Детское питание" href="http://www.mladenec-shop.ru/index.php?cat=207011&amp;manuf_id=1186&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B42&#37;5D=&amp;filter&#37;5B43&#37;5D=&amp;filter&#37;5B44&#37;5D=&amp;filter&#37;5B45&#37;5D=&amp;filter&#37;5B46&#37;5D=&amp;filter&#37;5B202&#37;5D=&amp;filter&#37;5B287&#37;5D=" target="_blank">Фрутоняня</a>), <a title="Детские соки" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">Детские соки</a> (<a title="Детские соки" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">Спеленок</a> и <a title="Детские соки" href="http://www.mladenec-shop.ru/index.php?cat=207012&amp;manuf_id=1186&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B57&#37;5D=&amp;filter&#37;5B60&#37;5D=&amp;filter&#37;5B61&#37;5D=&amp;filter&#37;5B62&#37;5D=&amp;filter&#37;5B63&#37;5D=&amp;filter&#37;5B65&#37;5D=&amp;filter&#37;5B68&#37;5D=" target="_blank">Фрутоняня</a>), <a title="Детская вода" href="http://www.mladenec-shop.ru/?cat=207013" target="_blank">Детская вода Малютка</a> на сумму<strong> 6397 рублей</strong> и доставлены службой доставки Младенец.РУ в<strong> </strong>Детскую больницу г. Мытищи <strong>28.12.07 г.</strong></p>
 
  <p><strong>11)</strong> <strong>28.12.07 г</strong> в Детский дом по запросу волонтеров Отказники.Ру, в связи с отключением воды, было приобретено и доставлено<strong> 35 литров</strong> <a class="undefined" title="Детская вода" href="http://www.mladenec-shop.ru/index.php?cat=207013&amp;order=name&amp;all" target="_blank">Детской воды,</a><strong> </strong>на сумму <strong>1319 р.</strong></p>
 
  <p><strong>12) 07.02.08 г</strong> в Детский по запросу волонтеров Отказники.Ру были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207037" target="_blank">Детские ватные палочки</a> и <a title="Детская косметика" href="http://www.mladenec-shop.ru/index.php?cat=207049&amp;manuf_id=1167&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B121&#37;5D=&amp;filter&#37;5B122&#37;5D=&amp;filter&#37;5B130&#37;5D=" target="_blank">Детская косметика Наша мама</a> на сумму <strong>8511 рублей.</strong> </p>
 
  <p><strong>13) 08.02.08 г</strong> в Детскую Мытищинскую больницу по запросу волонтеров Отказники.РУ была доставлена <a title="детские коляски" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=8778" target="_blank">Детская коляска Колкрафт прогулочная</a> на сумму <strong>6175 рублей.</strong></p>
 
  <p><strong>14) 08.02.08 г </strong>в Детский дом по запросу волонтеров Отказники.Ру были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207011" target="_blank">Детское пюре,</a> <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=9360" target="_blank">Подгузники Памперс </a>и <a title="Детские игрушки" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=11098" target="_blank">Игрушка Ламазе &quot;Геометрический куб&quot;</a> на сумму <strong>2412 рублей.</strong></p>
 
  <p><strong>15) 27.03.08 г</strong> в Детский дом по запросу волонтеров Отказники.Ру было приобретено <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=70000122" target="_blank">Детское питание</a> (<a title="Детское пюре" href="http://www.mladenec-shop.ru/?cat=207011" target="_blank">пюре,</a> <a title="Детские молочные смеси" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">молочные смеси,</a> <a title="Детские товары" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">соки</a> и <a title="Детский чай" href="http://www.mladenec-shop.ru/?cat=207014" target="_blank">чай</a>)<strong> </strong>и <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207029" target="_blank">Детские подгузники Хаггис</a> на сумму <strong>27559 р.</strong></p>
 
  <p><strong>16) 11.04.08 г</strong> В Детский дом по запросу волонтеров Отказники.РУ было приобретено и доставлено 5 шт. <a title="Детские стульчики" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=10434" target="_blank">Детских стульчиков Литаф XL CHAIR </a>на сумму <strong>14280 рублей</strong>. <a name="blago"></a><a title="Детские товары" href="http://www.mladenec-shop.ru/blago" target="_blank"><strong>ФОТО ЗДЕСЬ.</strong></a> 
    <br />
   </p>
 
  <p><strong>17) 24.04.08 г </strong>В детскую больницу зпросам волонтеров Отказники.РУ был приобретен и доставлен<a title="Детский сок" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=3985" target="_blank"> Детский сок Hipp Хипп ORS - 200</a> на сумму <strong>4454 рублей.</strong> </p>
 
  <p><strong>18) 28.04.08 г</strong> в Детский дом по запросу волонтеров Отказники.РУ была приобретена и даставлена <a title="Детская вода" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=691" target="_blank">Детская вода Селивановская 7,5 литров</a> на сумму <strong>1201 рублей.</strong></p>
 
  <p><strong>19) 13.05.08 г </strong>В Детский дом по запросу волонтеров Отказники.РУ была приобретена и доставлена <a title="Детская вода" href="http://www.mladenec-shop.ru/?cat=207013" target="_blank">Детская вода,</a> <a title="Детская косметика" href="http://www.mladenec-shop.ru/?page=mangoods&amp;manuf_id=1021" target="_blank">Детская косметика,</a> <a title="Средства для стирки" href="http://www.mladenec-shop.ru/?cat=207026" target="_blank">Средства для стирки</a> и <a title="Стерилизатор" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=9301" target="_blank">Стерилизатор Авент для СВЧ-печи</a> на сумму <strong>14163 р.</strong></p>
 
  <p><strong>20) 19.05.08 г </strong>В Детский дом по запросу волонтеров Отказники.РУ была приобретена и доставлена <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму <strong>9979 рублей. </strong></p>
 
  <p><strong>21) 20.05.08 г</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское пюре" href="http://www.mladenec-shop.ru/?cat=207011" target="_blank">Детское пюре,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">детские молочные смеси</a> и Средства для гигиены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">(косметика,</a> <a title="Детские пеленки" href="http://www.mladenec-shop.ru/?cat=207033" target="_blank">пеленки</a> и <a title="Детские салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">салфетки)</a> на сумму <strong>6767 рублей.</strong></p>
 
  <p><strong>22) 21.05.08 г</strong> В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское пюре" href="http://www.mladenec-shop.ru/?cat=207011" target="_blank">Детское пюре,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">детские молочные смеси</a> и Средства для гигиены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">(косметика,</a> <a title="Детские пеленки" href="http://www.mladenec-shop.ru/?cat=207033" target="_blank">пеленки</a> и <a title="Детские салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">салфетки)</a> на сумму <strong>18448 рублей. </strong></p>
 
  <p><strong>23) 27.06.08 г </strong>В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детскя вода" href="http://www.mladenec-shop.ru/index.php?cat=207013&amp;manuf_id=1162&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B25&#37;5D=" target="_blank">Детская вода Малютка,</a> <a class="undefined" title="Детский сок" href="http://www.mladenec-shop.ru/index.php?cat=207012&amp;manuf_id=1145&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B57&#37;5D=&amp;filter&#37;5B60&#37;5D=&amp;filter&#37;5B61&#37;5D=&amp;filter&#37;5B62&#37;5D=&amp;filter&#37;5B63&#37;5D=&amp;filter&#37;5B65&#37;5D=&amp;filter&#37;5B68&#37;5D=" target="_blank">Детский сок Бабушкино лукошко,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">детские молочные смеси</a> <a class="undefined" title="Детский стульчик" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=10123" target="_blank">Детские стульчики трансформеры Литаф</a> и Средства для гигиены <a class="undefined" title="Детские салфетки" href="http://www.mladenec-shop.ru/index.php?cat=207036&amp;manuf_id=1059&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B150&#37;5D=&amp;filter&#37;5B151&#37;5D=&amp;filter&#37;5B183&#37;5D=" target="_blank">(детские платочки Клинекс)</a> на сумму <strong>21708 рублей.</strong></p>
 
  <p><strong>24) 09.07.08 г </strong>В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детские молочные смеси" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси,</a> <a class="undefined" title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская кометика</a> и <a class="undefined" title="Средства для гигиены" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> на сумму <strong>6114 рублей.</strong></p>
 
  <p><strong>25) 23.07.08 г</strong> В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детские памперсы" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники,</a> <a title="Детские товары" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">средства для гигиены,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=70000122" target="_blank">Детское питание</a> (<a title="Детские соки" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">соки, </a><a title="Детское печенье" href="http://www.mladenec-shop.ru/?cat=207016" target="_blank">печенье</a>), <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">детская косметика</a> и <a title="Детские стульчики" href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=10123" target="_blank">Детские стульчики Литаф SIT N PLAY</a> на сумму<strong> <strong>22887 рублей.</strong></strong></p>
 
  <p><strong><strong>26) 29.07.08 г</strong> </strong>В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> и <a title="Детские товары" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">детские салфетки</a> на сумму <strong><strong><strong>5415 рублей.</strong></strong></strong></p>
 
  <p><strong><strong>27) 11.08.08 г </strong></strong>В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детские молочные смеси" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси,</a> на сумму<strong> <strong>18729 рублей.</strong></strong></p>
 
  <p><strong>28)</strong> <strong><strong>08.09.08 г </strong></strong>В Мытищинскую Городскую клиническую Больницу по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское пюре" href="http://www.mladenec-shop.ru/?cat=207011" target="_blank">Детское пюре</a> и Средства для гигиены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">(косметика,</a> <a title="Детские пеленки" href="http://www.mladenec-shop.ru/?cat=207033" target="_blank">пеленки</a> и <a title="Детские салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">салфетки)</a> на сумму<strong> <strong>7923 рублей.</strong></strong></p>
 
  <p><strong>29)</strong> <strong><strong>08.09.08 г </strong></strong>В Мытищинский дом ребенка по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси</a> и Средства для гигиены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">(косметика,</a> <a title="Детские пеленки" href="http://www.mladenec-shop.ru/?cat=207033" target="_blank">пеленки</a> и <a title="Детские салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">салфетки)</a> на сумму<strong> <strong>20288 рублей.</strong></strong></p>
 
  <p><strong>30) 15.09.08 г</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и <a title="Детские памперсы" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники </a>на сумму <strong>12279 рублей.</strong></p>
 
  <p><strong><strong>31) 25.09.08 г </strong></strong>В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Для младенцев" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для ухода и гигиены</a> (<a title="Детские весы" href="http://www.mladenec-shop.ru/?cat=12" target="_blank">детские весы,</a> <a title="Салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">детские салфетки </a>, <a title="детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">детская косметика</a>) и <a title="Детские стульчики" href="http://www.mladenec-shop.ru/index.php?cat=99888471&amp;manuf_id=1067&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B55&#37;5D=" target="_blank">Детские стульчики Литаф</a> на сумму<strong> <strong>37438 рублей.</strong></strong></p>
 <strong>32) 02.10.08 г</strong> в Детский дом по запросу волонтеров Отказники.Ру было приобретено и доставлено<strong> 145 литров</strong> <a class="undefined" title="Детская вода" href="http://www.mladenec-shop.ru/index.php?cat=207013&amp;order=name&amp;all" target="_blank">Детской воды,</a><strong> </strong>на сумму <strong>1583 рублей. </strong> 
  <p><strong>33) 20.10.08 г</strong> в Мытищинский Детский дом ребенка по запросу волонтеров Отказники.Ру были приобретены и доставлены <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank"><strong>Детские подгузники</strong></a><strong>, </strong><a class="undefined" title="Салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank"><strong>детские салфетки</strong></a><strong> и </strong><a class="undefined" title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank"><strong>детская косметика</strong></a> на сумму <strong>10119 рублей.</strong></p>
 
  <p><strong>34) 24.10.08 г </strong>В Детский дом по запросу волонтеров Отказники.РУ былы приобретены и доставлены<a title="Для младенцев" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для ухода и гигиены</a> ( <a title="Салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">детские салфетки </a>, <a title="детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">детская косметика</a>), <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank"><strong>Детские подгузники</strong></a> и <a title="Детские стульчики" href="http://www.mladenec-shop.ru/index.php?cat=99888471&amp;manuf_id=1067&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B55&#37;5D=" target="_blank">Детские стульчики Литаф</a> на сумму<strong> 36374<strong> рублей.</strong></strong></p>
 
  <p><strong>35)</strong> <strong>10.11.08 г </strong>В Мытищинскую Городскую клиническую Больницу по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси</a> на сумму<strong> 10409<strong> рублей.</strong></strong></p>
 
  <p><strong>36)</strong> <strong><strong>04.12.08 г </strong></strong>В Мытищинский дом ребенка по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси</a> на сумму<strong> <strong>11261 рублей.</strong></strong></p>
 
  <p><strong>37) 23.12.08 г </strong>В Детский дом по запросу волонтеров Отказники.РУ былы приобретены и доставлены<a title="Для младенцев" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для ухода и гигиены</a> ( <a title="Салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">детские салфетки </a>, <a title="детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">детская косметика</a>) на сумму<strong> 96120<strong> рублей.</strong></strong></p>
 
  <p><strong>38) 09.02.09 г</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси</a> на сумму <strong>4855 рублей.</strong></p>
 
  <p><strong>39) 03.04.09 г</strong> в Детскую Мытищинскую больницу по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детские молочные смеси</a> и <a title="Авент" href="http://www.mladenec-shop.ru/index.php?cat=207041&amp;manuf_id=1005&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B172&#37;5D=&amp;filter&#37;5B174&#37;5D=&amp;filter&#37;5B176&#37;5D=&amp;filter&#37;5B178&#37;5D=&amp;filter&#37;5B180&#37;5D=&amp;filter&#37;5B181&#37;5D=" target="_blank">Средства для кормления (бутылочки и соски Авент)</a> на сумму <strong>7920 рублей.</strong></p>
 
  <p><strong>40) 07.04.09 г</strong> В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> и <a title="Детские стульчики" href="http://www.mladenec-shop.ru/?cat=99888471" target="_blank">Детские стульчики</a> на сумму<strong> 48615 рублей.</strong></p>
 
  <p><strong>41) 10.04.09 г</strong> В Детский дом по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> и <a title="Детские стульчики" href="http://www.mladenec-shop.ru/?cat=99888471" target="_blank">Детские стульчики</a> на сумму<strong> 31772 рублей.</strong></p>
 
  <p><strong>42) 14.04.09 г</strong> в Детскую Мытищинскую больницу по запросу волонтеров Отказники.РУ была приобретена и доставлена <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детская молочная смесь</a> на сумму <strong>14430 рублей.</strong></p>
 
  <p><strong>43) 25.04.09 г </strong>В Детский дом по запросу волонтеров Отказники.РУ былы приобретены и доставлены<a title="Для младенцев" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для ухода и гигиены</a> ( <a title="Салфетки" href="http://www.mladenec-shop.ru/?cat=207036" target="_blank">детские салфетки </a>, <a title="детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">детская косметика</a>) на сумму<strong> 2010<strong> рублей.</strong></strong></p>
 
  <p><strong>44) 24.04.09 г</strong> в Детский дом по запросу волонтеров Отказники.РУ была приобретена и даставлена <a title="Детская вода" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=691" target="_blank">Детская вода Селивановская 5 литров</a> на сумму <strong>1462 рублей.</strong></p>
 
  <p><strong>45) 22.04.09 г</strong> в Детский дом по запросу волонтеров Отказники.РУ была приобретена и даставлена <a title="Детская вода" href="http://www.mladenec-shop.ru/?page=desc&amp;pid=691" target="_blank">Детская вода Селивановская 7,5 литров</a> на сумму <strong>1498 рублей.</strong></p>
 
  <p><strong>46) 28.05.09 г</strong> В Распределительный центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика.</a> <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены,</a> <a title="Детские соки" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">Детские соки</a> и <a title="Детская вода" href="http://www.mladenec-shop.ru/?cat=207013" target="_blank">Детская вода</a> на сумму <strong>50211 рублей.</strong></p>
 
  <p><strong>47) 09.06.09 г</strong> В Распределительный центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> <a title="Детские каши" href="http://www.mladenec-shop.ru/?cat=207010" target="_blank">Детские каши, </a><a title="Детские соки" href="http://www.mladenec-shop.ru/?cat=207012" target="_blank">Детские соки</a> и <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>6559 рублей.</strong></p>
 
  <p><strong>48) 29.06.09 г</strong> В Распределительный центр по запросу волонтеров Отказники.РУ была приобретена и доставлена <a title="вода" href="http://www.mladenec-shop.ru/?cat=207013" target="_blank">Детская вода</a> на сумму <strong>1767 рублей.</strong></p>
 
  <p><strong>49) 27.07.09 г</strong> В Распределительный центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму <strong>9654  рублей.</strong></p>
 
  <p><strong>50) 19.08.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники,</a> <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и <a title="весы" href="http://www.mladenec-shop.ru/?cat=12" target="_blank">Детские весы</a> на сумму <strong>35304  рублей.</strong></p>
 
  <p><strong>51) 03.09.09 г</strong> В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="цу" href="http://www.mladenec-shop.ru/?cat=70000001" target="_blank">Детские ходунки</a> на сумму<strong> 38 030 рублей.</strong></p>
 <strong>52) 14.09.09 г</strong> в Детскую больницу №9 им.Сперанского по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="цуа" href="http://www.mladenec-shop.ru/?cat=99888471" target="_blank">Детские стульчики</a> на сумму <strong>33168 рублей</strong> 
  <p><strong>53) 14.09.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и<a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>16611  рублей.</strong></p>
 
  <p><strong>54) 08.10.09 г</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>13053  рублей.</strong></p>
 
  <p><strong>55) 08.10.09 г</strong> в Детскую больницу №9 им.Сперанского по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> на сумму <strong>5430  рублей.</strong></p>
 
  <p><strong>56) 15.10.09 г</strong> В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="цу" href="http://www.mladenec-shop.ru/?cat=70000001" target="_blank">Детские ходунки</a> на сумму<strong> 30 250 рублей.</strong></p>
 
  <p><strong>57) 19.10.09 г</strong> В Мытищинскую Городскую Клиническую Больницу для детей сирот было приобретено и доставлено <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму <strong>18 588 рублей.</strong></p>
 
  <p><strong>58) 29.10.09 г</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>16 965  рублей.</strong></p>
 
  <p><strong>59) 29.10.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и<a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>58 240  рублей.</strong></p>
 
  <p><strong>60) 10.11.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и<a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>34 595  рублей.</strong></p>
 
  <p><strong>61) </strong><strong>12.11.09 г</strong> В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="цу" href="http://www.mladenec-shop.ru/?cat=70000001" target="_blank">Детские ходунки</a> на сумму<strong> 24 352 рублей.</strong></p>
 
  <p><strong>62) 23.11.09 г</strong> В Мытищинскую Городскую Клиническую Больницу для детей сирот были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика,</a> на сумму <strong>31 273 рублей.</strong></p>
 
  <p><strong>63) 30.11.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и<a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>2 993  рублей.</strong> </p>
 
  <p><strong>64) 08.12.09 г</strong> В Мытищинскую Городскую Клиническую Больницу для детей сирот было приобретено и доставлено <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> на сумму <strong>9 630  рублей.</strong></p>
 
  <p><strong>65) </strong><strong>18.12.09 г</strong> В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> на сумму<strong> 31 471 рублей.</strong></p>
 
  <p><strong>66) 22.12.09 г</strong> В Мытищинскую Городскую Клиническую Больницу для детей сирот было приобретено и доставлено <a title="1" href="http://www.mladenec-shop.ru/?cat=207022" target="_blank">Игрушки</a> на сумму <strong>14 754  рублей</strong></p>
 
  <p><strong>67) 22.12.09 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и<a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>4 383  рублей.</strong></p>
 
  <p><strong>68) 01.02.10 г</strong> В Распределительный  центр по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> Средства для гигиены</a>  на сумму <strong>13 054  рублей.</strong></p>
 
  <p><strong>69) 04.02.10 г.</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму <strong>18 620  рублей.</strong></p>
 
  <p><strong>70) 05.02.10 г</strong>. В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a>  на сумму<strong> 29 107 рублей.</strong></p>
 
  <p><strong>71) 19.02.10 г</strong>. В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> на сумму <strong>6 037  рублей.</strong></p>
 
  <p><strong>72) </strong><strong>25.03.10 г</strong>. В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a>  на сумму<strong> 28 340 рублей.</strong></p>
 
  <p><strong>73) </strong><strong>10.04.10 г</strong>. В Кашинский дом ребенка были приобретены и доставлены <a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a>  на сумму<strong> 30 169 рублей.</strong> </p>
 
  <p><strong>74) </strong><strong>12.04.10 г</strong>.В пункт сбора помощи в Южном Бутово по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> </a><a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>33 110  рублей.</strong></p>
 
  <p><strong>75) </strong><strong>12.04.10 г</strong>. <a class="title" href="http://www.otkazniki.ru/centers.php?ocd=view&amp;id=13">Пункт сбора помощи в Перово</a> по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> </a><a title="Детская косметика" href="http://www.mladenec-shop.ru/?cat=207025" target="_blank">Детская косметика</a> и <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>44 596  рублей.</strong></p>
 
  <p><strong>76) </strong><strong>13.04.10 г</strong>. В Московский НИИ Педиатрии и Детской Хирургии были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"> </a><a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму <strong>4 415  рублей.</strong></p>
 
  <p><strong>72) </strong><strong>29.04.10 г</strong>. В Мытищинский дом ребенка были приобретены и доставлены <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> и <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a>  на сумму<strong> 29 497 рублей.</strong></p>
 
  <p><strong>73) </strong><strong>19.05.10 г</strong>. В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a>  на сумму<strong> 4 761 рубль.</strong></p>
 
  <p><strong>74) </strong><strong>25.05.10 г</strong>. В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank">Детское питание</a> на сумму<strong> 20 119 рублей.</strong></p>
 
  <p><strong>75) </strong><strong>27.05.10 г</strong>. В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank">Средства для гигиены</a> и <a class="undefined" title="Детские подгузники" href="http://www.mladenec-shop.ru/?cat=207019" target="_blank">Детские подгузники</a> на сумму <strong>22 791  рублей.</strong></p>
 
  <p><strong>76) </strong><strong>05.06.10 г</strong>. В Бесплатный центр Социальной Реабилитации для наркозависимых и алкоголиков для новорожденного ребенка были доставлены Заменитель <a href="http://www.mladenec-shop.ru/index.php?page=desc&amp;pid=11791" target="_blank">НАН кисломолочный 2 400гр.</a> и <a href="http://www.mladenec-shop.ru/index.php?cat=207012&amp;manuf_id=3000&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B57&#37;5D=&amp;filter&#37;5B60&#37;5D=&amp;filter&#37;5B61&#37;5D=&amp;filter&#37;5B62&#37;5D=&amp;filter&#37;5B63&#37;5D=&amp;filter&#37;5B65&#37;5D=&amp;filter&#37;5B68&#37;5D=" target="_self">соки Малышам</a> на сумму <strong>2 371  рубль.</strong></p>
 <strong><strong><strong>77) </strong></strong></strong><strong>25.06.10 г</strong>. В Кашинский дом ребенка были приобретены и доставлены детские <a href="http://www.mladenec-shop.ru/index.php?cat=12&amp;manuf_id=1071&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B162&#37;5D=&amp;filter&#37;5B163&#37;5D=&amp;filter&#37;5B164&#37;5D=" target="_self">весы Maman</a> на сумму<strong> 4 425 рублей. </strong> 
  <p><strong>78) 29.06.10 г</strong> <span class="Apple-style-span">В Мытищинский дом ребенка были приобретены и доставлены</span> <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"><strong>Средства для гигиены</strong></a><strong> и </strong><a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank"><strong>Детское питание</strong></a> на сумму <strong>28 088 рублей.</strong></p>
 
  <p><strong>79) 05.07.10 г.</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены<a href="http://www.mladenec-shop.ru/index.php?cat=99888482&amp;manuf_id=1005&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B138&#37;5D=" target="_blank"> <strong>Стерилизаторы Авент</strong></a> и<strong> </strong><a href="http://www.mladenec-shop.ru/?cat=207030" target="_blank"><strong>Детские подгузники Pampers</strong></a> на сумму <strong>21 395  рублей.</strong></p>
 
  <p><strong>80) 27.07.10 г</strong> В Мытищинский дом ребенка были приобретены и доставлены<strong> </strong><a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"><strong>Средства для гигиены</strong></a> и <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank"><strong>Детское питание</strong></a> на сумму <strong>24 500 рублей.</strong></p>
 
  <p><strong>81) 05.07.10 г.</strong> В Бакулевский центр, в отделение экстренной хирургии новорожденных по запросу волонтеров Отказники.РУ были приобретены и доставлены<a href="http://www.mladenec-shop.ru/index.php?cat=99888482&amp;manuf_id=1005&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B138&#37;5D=" target="_blank"><strong> </strong></a><a href="http://www.mladenec-shop.ru/?cat=207009" target="_blank"><strong>Молочные смеси</strong></a> и<strong> </strong><a href="http://www.mladenec-shop.ru/?cat=207009" target="_blank"><strong>Пеленки</strong></a> на сумму <strong>5 200  рублей.</strong></p>
 
  <p><strong>82) 12.04.10 г.</strong> В пункт сбора помощи в Перово по запросу волонтеров Отказники.РУ были приобретены и доставлены <a href="http://www.mladenec-shop.ru/index.php?cat=12&amp;manuf_id=&amp;age=&#37;EF&#37;EE+&#37;E2&#37;EE&#37;E7&#37;F0&#37;E0&#37;F1&#37;F2&#37;F3&amp;order=name&amp;filter&#37;5B162&#37;5D=633&amp;filter&#37;5B163&#37;5D=&amp;filter&#37;5B164&#37;5D=" target="_blank"> <strong>Детские весы</strong></a> на сумму <strong>4 550  рублей.</strong></p>
 
  <p><strong>83) 27.07.10 г</strong> В Мытищинский дом ребенка были приобретены и доставлены <a title="Детская гигиена" href="http://www.mladenec-shop.ru/?cat=207020" target="_blank"><strong>Средства для гигиены</strong></a> и <a title="Детское питание" href="http://www.mladenec-shop.ru/?cat=207009" target="_blank"><strong>Детское питание</strong></a> на сумму <strong>29 945 рублей.</strong></p>
 
  <p> <b><img height="700" width="495" border="0" src="http://www.mladenec-shop.ru/data/10,04,2010.jpg" alt="10,04,2010.jpg" title="10,04,2010.jpg" /></b></p>
 
  <p><b><img height="700" width="500" border="0" src="http://www.mladenec-shop.ru/data/2009.jpg" alt="2009.jpg" title="2009.jpg" /></b></p>
 
  <p><b><img height="700" width="500" border="0" src="http://www.mladenec-shop.ru/data/blagotvoritelnost_000001_1.gif" alt="blagotvoritelnost_000001_1.gif" title="blagotvoritelnost_000001_1.gif" /> </b></p>
 </div>
 <?$APPLICATION->IncludeComponent(
	"bitrix:main.site.selector",
	"",
	Array(
	)
);?> 
<br />
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>